### ISSUE TITLE
Doesnt seem to be working.

### ISSUE THREAD

**Issue by bnichs5** [NguyenKhong/CrackNetDrive3#3]
Can you help? I'm getting 4 different "success ________ has been terminated"
then a " running on 127.0.0.1:52201/"

press ctrl +c to quit. 

Thats it but it wont let me log into netdrive.

**Comment by NBSDEVApp** [comment]
Same issue

**Comment by NBSDEVApp** [comment]
Same issue but no "sucess" just " running on "127.0.0.1:52201/  press ctrl +c to quit." 
And no login work.
Thanks for help

**Comment by uaktags** [comment]
It works, follow the video.

**Comment by bnichs5** [comment]
I got it to work.
